name: 同步evine-shell
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  merge-branch:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
        with:
          persist-credentials: fals 

      - name: git-sync monk-coder to github with private key
        uses: wei/git-sync@v3
        with:
          source_repo: "git@gitee.com:evine/jd_shell.git"
          source_branch: "master"
          destination_repo: "nxppru/shell"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
